In [1]:
from pynq import Overlay
import numpy as np
import random
from pynq import allocate

In [2]:
# stream_overlay = Overlay("/home/xilinx/pynq/overlays/fir_filter/fir_filter.bit")
stream_overlay = Overlay("/home/xilinx/pynq/overlays/project/decoder/process_next_bit.bit")
# stream_overlay?

In [3]:
dma = stream_overlay.processNextBit.axi_dma

In [4]:
input_buffer = None
output_buffer = None

In [5]:
import math

In [6]:
# input_buffer[:] = [random.randint(0, 100) for k in range(11)]
bits = [1, 0, 1, 1, 1, 0, 0, 0]
length = len(bits)
if input_buffer is not None:
    del input_buffer
if output_buffer is not None:
    del output_buffer

# output_length = math.ceil(length / 4)
input_buffer = allocate(shape=(length,), dtype=np.int32)
output_buffer = allocate(shape=(length,), dtype=np.int32)
input_buffer[:] = bits[:]
print(input_buffer)

[1 0 1 1 1 0 0 0]


In [7]:
def send_data_in():
    dma.sendchannel.transfer(input_buffer)
    dma.sendchannel.wait()

In [8]:
def recv_data_out():
    dma.recvchannel.transfer(output_buffer)
    dma.recvchannel.wait()

In [9]:
def run_kernel():
    send_data_in()
    recv_data_out()

In [10]:
# dma.sendchannel.start()
print(input_buffer)
dma.sendchannel.transfer(input_buffer)
dma.sendchannel.wait()
print(input_buffer)

[1 0 1 1 1 0 0 0]
[1 0 1 1 1 0 0 0]


In [11]:
# dma.recvchannel.start()
print(output_buffer)
dma.recvchannel.transfer(output_buffer)
dma.recvchannel.wait()
print(output_buffer)

[0 0 0 0 0 0 0 0]
[0 1 1 4 0 0 0 0]


In [12]:
# run_kernel()
letters = [5, 20, 9, 1, 14, 13, 19, 21, 18, 23, 4, 11, 7, 15, 8, 22, 6, 31, 12, 31, 16, 10, 2, 24, 3, 25, 26, 17]